import { notFound } from "next/navigation";
import { SiteFooter, SiteHeader } from "../../site-chrome";
import { researchProjects } from "../../site-data";
import { researchStrands } from "../strand-data";
function ProjectParagraph({text}:{text:string}){const parts=text.split("Figure 1");return <>{parts.map((part,index)=><span key={index}>{index>0&&<strong>Figure 1</strong>}{part}</span>)}</>}
const allProjects = [...researchStrands, ...researchProjects.filter((project) => project.slug !== "denali-begguya")].map((project) => project.slug === "methods" ? {
  ...project,
  title: "Melting ice, analyzing geochemistry, and running models",
  summary: "My research navigates ice-core melter systems, trace metal and isotope geochemistry, large climate datasets, and atmospheric chemistry models.",
} : project);
export function generateStaticParams(){return allProjects.map(p=>({slug:p.slug}))}
export default async function ProjectPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=allProjects.find(x=>x.slug===slug);if(!p)notFound();const isJetStream=p.slug==="polar-jet-stream-waviness";return <main><SiteHeader/><article className="project-page"><header className="project-cover wrap"><div><p className="eyebrow"><span/>{p.tag}</p><h1>{p.title}</h1><p>{p.summary}</p></div><figure className={p.imageCaption?"project-cover-captioned":undefined}>{isJetStream?<><video className="research-program-video" autoPlay muted loop playsInline preload="metadata" poster="/images/jet-stream-print-res.jpg"><source src="/videos/jetstream-loop.mp4" type="video/mp4"/></video><img className="research-program-video-fallback" src="/images/jet-stream-print-res.jpg" alt="Polar jet stream flowing across North America"/></>:<img src={p.image} alt={p.imageAlt}/>}<figcaption>{p.imageCaption??(isJetStream?"Polar jet stream variability":"Field archive · Jacob Chalif")}</figcaption></figure></header><section className="project-body wrap"><aside><span>{p.kicker}</span></aside><div>{p.body.map((x,i)=><p key={i}><ProjectParagraph text={x}/></p>)}</div></section>{p.relatedPublications&&<section className="research-citations project-citations wrap"><p className="eyebrow"><span/>Related publications</p><div className="research-citation-grid">{p.relatedPublications.map(publication=>{const citation=<><div><strong>{publication.authors} ({publication.year})</strong>{publication.href&&<span>↗</span>}</div><h3>{publication.title}</h3><p>{publication.journal}</p></>;return publication.href?<a href={publication.href} target="_blank" rel="noreferrer" key={publication.href}>{citation}</a>:<article key={publication.title}>{citation}</article>})}</div></section>}{p.figure&&<figure className="science-figure wrap"><img src={p.figure} alt={p.figureAlt}/><figcaption>{p.figureCaption?<><strong>Figure 1.</strong> {p.figureCaption}</>:p.credit}</figcaption></figure>}<div className="next-link wrap"><a href="/research">← All research</a></div></article><SiteFooter/></main>}
