import type { Project } from "../site-data";

export const researchStrands: Project[] = [
  {
    slug: "southeastern-siberian-wildfire",
    shortTitle: "Siberian wildfire",
    title: "Siberian wildfire",
    tag: "North Pacific atmosphere",
    kicker: "Begguya · Wildfires · Paleoclimate · Aerosols",
    summary: "Reconstructing 1,200 years of southeastern Siberian fire and the seasonal climate dynamics that control burning.",
    body: [
      "The boreal forests of southeastern Siberia are among the most fire-prone ecosystems on Earth, yet direct observations of wildfire activity extend back only to the 2000s. To understand how fire has changed over longer timescales, I use ice cores from the Begguya summit plateau in Denali National Park, Alaska. As illustrated in Figure 1, smoke from springtime Siberian wildfires is carried across the North Pacific, where snowfall at Begguya preserves black carbon from those fires.",
      "The 1,200-year ice-core record reveals that southeastern Siberian fire activity was relatively high during the warm Medieval Climate Anomaly, declined during the cooler Little Ice Age, and has increased rapidly since the late nineteenth century alongside industrial-era warming. These long-term changes are closely linked to climate: warmer late winters promote earlier snowmelt and a longer fire season, while shifts in the East Asian Summer Monsoon influence fuel moisture and the frequency of large wildfires. Surprisingly, the record also shows little evidence that industrial pollution substantially increased black carbon reaching Begguya. Together, these findings provide a long-term perspective on how boreal fire responds to climate change while improving our understanding of the atmospheric processes that connect Asia, the North Pacific, and the Arctic.",
    ],
    image: "/images/siberian-wildfire-reuters.webp",
    imageAlt: "A large boreal wildfire producing a dense smoke plume over Canada",
    imageCaption: "Boreal fires in Canada • Alberta Wildfire Service",
    figure: "/figures/wildfire-overview.png",
    figureAlt: "Overview of the Begguya ice-core wildfire reconstruction",
    credit: "Figure: Jacob Chalif",
    figureCaption: "Springtime wildfires in southeastern Siberia produce smoke that is transported across the North Pacific to the Begguya ice core site in Denali National Park, Alaska. The panels show the seasonal cycle of climate, fire emissions, and black carbon preserved in the ice, along with the geographic distribution and timing of boreal fire activity across southeastern Siberia.",
    relatedPublications: [
      {
        authors: "Chalif et al.",
        year: "2026",
        title: "Seasonal climate drivers of southeastern Siberian wildfire over the last 1,200 years",
        journal: "In review",
      },
    ],
  },
  {
    slug: "marine-sulfur-cycle",
    shortTitle: "Marine sulfur cycle",
    title: "Marine sulfur cycle",
    tag: "Atmospheric chemistry",
    kicker: "Begguya · Methanesulfonic acid · Oxidation chemistry · Pollution",
    summary: "Separating biological change from pollution-driven shifts in atmospheric oxidation and methanesulfonic acid (MSA).",
    body: [
      "Marine phytoplankton release dimethyl sulfide (DMS), a gas that helps form atmospheric aerosols and influences cloud formation over the oceans. One of its oxidation products, methanesulfonic acid (MSA), is preserved in polar ice cores and has long been used as a proxy for past marine productivity. However, many Arctic ice-core records show a sharp decline in MSA beginning during the Industrial Era—a trend that was widely interpreted as evidence of crashing phytoplankton populations.",
      "Using ice cores from Denali and Greenland together with atmospheric chemistry modeling, we found a different explanation. Rather than reflecting widespread changes in ocean biology, the decline in MSA is primarily the result of anthropogenic air pollution altering the chemistry of the atmosphere. As illustrated in Figure 1, pollution changes the oxidation pathways of DMS, causing less MSA to form before the air masses reach the Arctic. This work demonstrates that industrial emissions have fundamentally altered atmospheric chemistry even in Earth's most remote regions, while also redefining how scientists interpret one of the Arctic's most important ice-core proxies for the marine environment.",
    ],
    image: "/images/gulf-of-alaska-phytoplankton-nasa.jpg",
    imageAlt: "Satellite view of a phytoplankton bloom in the Gulf of Alaska",
    imageCaption: "NASA • Phytoplankton bloom in Gulf of Alaska",
    figure: "/figures/marine-sulfur-schematic.png",
    figureAlt: "Schematic showing how pollution alters dimethyl sulfide oxidation and reduces methanesulfonic acid deposition in Arctic ice",
    credit: "Figure: Nature Geoscience",
    figureCaption: "Human-caused air pollution has altered the atmospheric chemistry of marine sulfur. By changing the oxidation pathways of dimethyl sulfide (DMS), pollution causes a greater fraction of DMS to be converted into sulfate (SO₄²⁻) and a smaller fraction into methanesulfonic acid (MSA), reducing the amount of MSA preserved in Arctic ice cores.",
    relatedPublications: [
      {
        authors: "Chalif et al.",
        year: "2024",
        title: "Pollution drives multidecadal decline in subarctic methanesulfonic acid",
        journal: "Nature Geoscience 17, 1016–1021",
        href: "https://doi.org/10.1038/s41561-024-01543-w",
      },
      {
        authors: "Jongebloed et al.",
        year: "2025",
        title: "Dimethyl sulfide chemistry over the industrial era: comparison of key oxidation mechanisms and long-term observations",
        journal: "Atmospheric Chemistry and Physics 25, 4083–4106",
        href: "https://doi.org/10.5194/acp-25-4083-2025",
      },
    ],
  },
  {
    slug: "anthropogenic-pollution",
    shortTitle: "Anthropogenic pollution",
    title: "Pollution in the North Pacific",
    tag: "North Pacific atmosphere",
    kicker: "Lead · Nitrate · PFAS",
    summary: "Tracing industrial emissions that reach the remote North Pacific atmosphere.",
    body: [
      "Industrialization has transformed the chemistry of the North Pacific atmosphere, with pollutants now reaching even the most remote mountain glaciers in Alaska and the Yukon. Ice cores preserve a long-term record of these changes, allowing us to reconstruct how emissions from human activities have evolved over the past centuries. My research integrates trace metal concentrations, Pb isotopes, black carbon, sulfur chemistry, and emerging contaminants (e.g., PFAS) to understand both the history of atmospheric pollution and the processes that transport it across the Pacific.",
      "My work has shown that anthropogenic emissions can fundamentally alter atmospheric chemistry in unexpected ways. In Arctic ice cores, I demonstrated that industrial pollution changes the oxidation pathways of marine sulfur, reducing the amount of methanesulfonic acid (MSA) formed from dimethyl sulfide and reshaping one of the Arctic's most widely used climate proxies. At the same time, my research on black carbon from southeast Siberian wildfires found surprisingly little evidence that twentieth-century industrial emissions increased black carbon reaching Begguya, highlighting the importance of atmospheric transport and removal processes. Complementary work using lead concentrations and isotopes traces the changing sources of industrial pollution across the Pacific, revealing how emissions from North America and Asia have evolved through time.",
      "Current work on the Eclipse Icefield in the St. Elias Mountains is expanding these records to include emerging contaminants such as PFAS (\"forever chemicals\"), heavy metals, black carbon, and other aerosol tracers. Together, these records provide a powerful archive of how human activities have changed the composition of the North Pacific atmosphere, while helping to distinguish changes in emissions from changes in atmospheric transport and chemistry.",
    ],
    image: "/images/creusot-smokestacks-brouet.jpg",
    imageAlt: "Auguste Brouet print depicting smokestacks at the Creusot Works",
    imageCaption: "At the Creusot Works: The Smokestacks • c. 1902–41 • Auguste Brouet",
    relatedPublications: [
      {
        authors: "Chalif et al.",
        year: "2024",
        title: "Pollution drives multidecadal decline in subarctic methanesulfonic acid",
        journal: "Nature Geoscience 17, 1016–1021",
        href: "https://doi.org/10.1038/s41561-024-01543-w",
      },
      {
        authors: "Chalif et al.",
        year: "2026",
        title: "Seasonal climate drivers of southeastern Siberian wildfire over the last 1,200 years",
        journal: "In review",
      },
      {
        authors: "Koffman et al.",
        year: "2026",
        title: "Disentangling source versus transport effects on atmospheric dust in alpine ice and snow",
        journal: "In review",
      },
    ],
  },
  {
    slug: "impurity-geochemistry-blue-ice",
    shortTitle: "Impurity geochemistry",
    title: "Impurity geochemistry at blue ice areas",
    tag: "Oldest ice",
    kicker: "COLDEX · Allan Hills · Geochemistry",
    summary: "Performing a variety of chemical measurements to evaluate how blue ice areas archive climate information.",
    body: [
      "The oldest ice preserved in Antarctica offers an unprecedented window into Earth's past, but it has also spent millions of years flowing through the ice sheet before reaching the surface. During that journey, interactions with the glacier bed can introduce minerals, dust, and dissolved chemical species that complicate the interpretation of climate records. At the same time, deformation within the ice sheet can alter the relative proportions of glacial and interglacial ice preserved within an individual sample. Understanding these processes is essential for determining how faithfully Earth's oldest ice records past climate.",
      "In this project, I use trace elements, major ions, particle size distributions, and scanning electron microscopy to characterize the impurities preserved in the Allan Hills ice cores. These measurements reveal that many impurity-rich layers contain material incorporated from the glacier bed rather than atmospheric deposition alone, providing new insight into how basal processes modify ancient ice. By combining these observations with climate proxies, we can distinguish between signals caused by basal alteration and those that reflect changes in atmospheric composition or climate, while also investigating how different glacial and interglacial weightings may be preserved within neighboring packets of ancient ice.",
    ],
    image: "/images/lab-process.jpg",
    imageAlt: "Decontaminating an Allan Hills ice core in the Dartmouth ice-core freezer",
    imageCaption: "Decontaminating Allan Hills ice",
    relatedPublications: [
      {
        authors: "Hudak et al.",
        year: "2026",
        title: "Fidelity and stratigraphy of the Antarctic Allan Hills old ice archive from Continuous Flow Analysis",
        journal: "In review",
      },
      {
        authors: "Choi et al.",
        year: "2026",
        title: "Dust Record from Allan Hills Blue Ice: Towards Extending the Archive to 4000 ka",
        journal: "In review",
      },
    ],
  },
  {
    slug: "fine-scale-layering-oldest-ice",
    shortTitle: "Fine-scale layering",
    title: "Fine-scale layering in Earth’s oldest ice",
    tag: "Oldest ice",
    kicker: "COLDEX · Allan Hills · Basal processes · Ice stratigraphy",
    summary: "Resolving cm-scale stratigraphy to understand how folding and basal processes alter climate signals in ancient ice.",
    body: [
      "The oldest Antarctic ice, found at the Allan Hills, is not preserved as a simple, continuous archive like a classic ice core. As glaciers flow over rugged bedrock, layers of ice become folded, compressed, and steeply tilted, creating abrupt \"age jumps\" where neighboring layers can differ in age by more than 100,000 years despite being separated by only a few centimeters. Because these layers cut diagonally across the core, samples taken from the same depth on opposite sides can represent entirely different ages and climate states, complicating the interpretation of Earth's oldest ice.",
      "In this work, we combined three-dimensional electrical conductivity measurements with water isotopes, greenhouse gases, argon dating, and high-resolution geochemical and particle analyses to reconstruct the geometry and composition of these layers. By accounting for their steep orientation and aligning all measurements on a shared, dip-adjusted depth scale, we showed that measurements from different parts of the core could be accurately compared. The chemistry and particle data further revealed that many of the layers represent distinct packets of ice containing different amounts of material incorporated from the glacier bed, rather than a single continuous climate record.",
      "Together, these results demonstrate how basal processes and ice deformation create the complex layering observed in the Allan Hills. This work provides a new framework for interpreting disturbed ice cores and aids efforts to use Earth's oldest ice to reconstruct past climate and atmospheric composition with greater confidence.",
    ],
    image: "/images/allan-hills-dust-sem.png",
    imageAlt: "Scanning electron microscope image of dust from Allan Hills ice",
    imageCaption: "SEM image of Allan Hills dust • Bess Koffman",
    figure: "/figures/fine-scale-layering-dip-adjustment.png",
    figureAlt: "Allan Hills ice-core measurements shown before and after adjustment for steeply tilted layers",
    figureCaption: "Layers in the Allan Hills ice core are steeply tilted, so samples at the same depth do not necessarily represent the same point in time. A dip-adjusted depth scale aligns measurements to the ice layers, enabling accurate comparison of different climate records. (Kirkpatrick et al., in prep)",
  },
  {
    slug: "polar-jet-stream-waviness",
    shortTitle: "Jet stream waviness",
    title: "Polar jet stream waviness",
    tag: "Climate dynamics",
    kicker: "Jet stream · Reanalysis · Self-organizing maps · Warming hole",
    summary: "Reconstructing changes in polar jet stream waviness since 1901 to separate natural variability from emerging climate-change signals.",
    body: [
      "The polar jet stream is a fast-moving ribbon of winds that steers winter storms and controls the movement of Arctic air across the Northern Hemisphere. In recent decades, unusually large waves in the jet stream have been linked to extreme cold outbreaks, winter storms, and persistent weather patterns. Whether these changes are driven by human-caused climate change or are part of the atmosphere's natural variability remains a central question in climate science.",
      "To investigate this, I developed a new 125-year reconstruction of North American winter jet stream waviness using self-organizing maps and multiple historical climate datasets. As shown in Figure 1, today's highly wavy jet stream is not unprecedented—the mid-twentieth century experienced similarly large meanders, despite occurring long before the satellite era. These episodes of enhanced waviness coincided with the eastern U.S. \"warming hole,\" and my work shows they were responsible for roughly two-thirds of its wintertime cooling. By placing recent atmospheric circulation in a century-long context, this research helps distinguish natural variability from long-term climate change and improves our understanding of the mechanisms behind weather extremes.",
    ],
    image: "/images/jet-stream-print-res.jpg",
    imageAlt: "Polar jet stream flowing across North America",
    imageCaption: "NASA • Jet Stream",
    figure: "/figures/jet-stream-waviness-timeline.webp",
    figureAlt: "A 125-year reconstruction of North American winter jet stream waviness",
    credit: "Figure: AGU Advances",
    figureCaption: "A 125-year reconstruction of North American winter jet stream waviness shows that highly meandering jet stream patterns are not unique to the satellite era. The jet stream was similarly—or even more—wavy during the mid-twentieth century, coinciding with the eastern U.S. \"warming hole,\" where increased cold-air outbreaks offset much of the global warming signal.",
    relatedPublications: [
      {
        authors: "Chalif et al.",
        year: "2025",
        title: "A wavier polar jet stream contributed to the mid-20th century winter warming hole in the United States",
        journal: "AGU Advances 6, e2024AV001399",
        href: "https://doi.org/10.1029/2024AV001399",
      },
    ],
  },
  {
    slug: "northeastern-temperature-extremes",
    shortTitle: "Temperature extremes",
    title: "Temperature extremes in the NE U.S.",
    tag: "Climate variability",
    kicker: "Cold snaps · Heat waves",
    summary: "Understanding how winter cold snaps and summer heat waves are changing across the northeastern United States.",
    body: [
      "We're investigating how the frequency, magnitude, and spatial extent of temperature extremes in the northeast U.S. are changing, as well as any circulation patterns driving these changes. More coming soon!",
    ],
    image: "/images/extreme-heat-reuters.webp",
    imageAlt: "Extreme heat warning sign in a dry desert landscape",
    imageCaption: "Reuters",
  },
];
